[build]
command = 'sed -i "s|{API_URL}|${REACT_APP_API_URL}|g" netlify.toml && yarn build'
publish = "build"

[context.production.environment]
REACT_APP_API_URL = "https://api.mathlab.academy"

[[redirects]]
from = "/api/*"
to = "{API_URL}/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
