export const CURRENT_USER_LOGIN_REQUEST = 'CURRENT_USER_LOGIN_REQUEST'
export const CURRENT_USER_UPDATE = 'CURRENT_USER_UPDATE'
export const CURRENT_USER_REMOVE = 'CURRENT_USER_REMOVE'

export const UI_LOCALE_UPDATE = 'UI_LOCALE_UPDATE'

export const ERROR_BOUNDARY_SET_ROOT_ERROR = 'ERROR_BOUNDARY_SET_ROOT_ERROR'

export const USER_ADD = 'USER_ADD'
export const USER_BULK_ADD = 'USER_BULK_ADD'
export const USER_REMOVE = 'USER_REMOVE'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_PAGE_ADD = 'USER_PAGE_ADD'
export const USER_PAGE_REMOVE = 'USER_PAGE_REMOVE'
export const USER_PAGE_REQUEST = 'USER_PAGE_REQUEST'
export const USER_PAGINATION_PURGE = 'USER_PAGINATION_PURGE'

export const COURSE_ADD = 'COURSE_ADD'
export const COURSE_BULK_ADD = 'COURSE_BULK_ADD'
export const COURSE_REMOVE = 'COURSE_REMOVE'
export const COURSE_UPDATE = 'COURSE_UPDATE'
export const COURSE_PAGE_ADD = 'COURSE_PAGE_ADD'
export const COURSE_PAGE_REMOVE = 'COURSE_PAGE_REMOVE'
export const COURSE_PAGE_REQUEST = 'COURSE_PAGE_REQUEST'
export const COURSE_PAGINATION_PURGE = 'COURSE_PAGINATION_PURGE'

export const COURSETAG_ADD = 'COURSETAG_ADD'
export const COURSETAG_BULK_ADD = 'COURSETAG_BULK_ADD'
export const COURSETAG_REMOVE = 'COURSETAG_REMOVE'
export const COURSETAG_UPDATE = 'COURSETAG_UPDATE'
export const COURSETAG_PAGE_ADD = 'COURSETAG_PAGE_ADD'
export const COURSETAG_PAGE_REMOVE = 'COURSETAG_PAGE_REMOVE'
export const COURSETAG_PAGE_REQUEST = 'COURSETAG_PAGE_REQUEST'
export const COURSETAG_PAGINATION_PURGE = 'COURSETAG_PAGINATION_PURGE'

export const MCQEXAM_ADD = 'MCQEXAM_ADD'
export const MCQEXAM_BULK_ADD = 'MCQEXAM_BULK_ADD'
export const MCQEXAM_REMOVE = 'MCQEXAM_REMOVE'
export const MCQEXAM_UPDATE = 'MCQEXAM_UPDATE'

export const CQEXAM_ADD = 'CQEXAM_ADD'
export const CQEXAM_BULK_ADD = 'CQEXAM_BULK_ADD'
export const CQEXAM_REMOVE = 'CQEXAM_REMOVE'
export const CQEXAM_UPDATE = 'CQEXAM_UPDATE'

export const MCQEXAMQUESTION_ADD = 'MCQEXAMQUESTION_ADD'
export const MCQEXAMQUESTION_BULK_ADD = 'MCQEXAMQUESTION_BULK_ADD'

export const MCQEXAMTRACKER_UPDATE = 'MCQEXAMTRACKER_UPDATE'

export const MCQSUBMISSION_BULK_ADD = 'MCQSUBMISSION_BULK_ADD'
export const MCQSUBMISSION_UPDATE = 'MCQSUBMISSION_UPDATE'

export const MCQ_ADD = 'MCQ_ADD'
export const MCQ_BULK_ADD = 'MCQ_BULK_ADD'
export const MCQ_REMOVE = 'MCQ_REMOVE'
export const MCQ_UPDATE = 'MCQ_UPDATE'
export const MCQ_PAGE_ADD = 'MCQ_PAGE_ADD'
export const MCQ_PAGE_REMOVE = 'MCQ_PAGE_REMOVE'
export const MCQ_PAGE_REQUEST = 'MCQ_PAGE_REQUEST'
export const MCQ_PAGINATION_PURGE = 'MCQ_PAGINATION_PURGE'

export const MCQANSWER_ADD = 'MCQANSWER_ADD'
export const MCQANSWER_BULK_ADD = 'MCQANSWER_BULK_ADD'

export const MCQTAG_ADD = 'MCQTAG_ADD'
export const MCQTAG_BULK_ADD = 'MCQTAG_BULK_ADD'
export const MCQTAG_REMOVE = 'MCQTAG_REMOVE'
export const MCQTAG_UPDATE = 'MCQTAG_UPDATE'
export const MCQTAG_PAGE_ADD = 'MCQTAG_PAGE_ADD'
export const MCQTAG_PAGE_REMOVE = 'MCQTAG_PAGE_REMOVE'
export const MCQTAG_PAGE_REQUEST = 'MCQTAG_PAGE_REQUEST'
export const MCQTAG_PAGINATION_PURGE = 'MCQTAG_PAGINATION_PURGE'

export const MCQIMAGE_BULK_ADD = 'MCQIMAGE_BULK_ADD'
export const MCQIMAGE_ADD = 'MCQIMAGE_ADD'
export const MCQIMAGE_TMP_ADD = 'MCQIMAGE_TMP_ADD'
export const MCQIMAGE_TMP_BULK_ADD = 'MCQIMAGE_TMP_BULK_ADD'

export const TRANSACTION_BULK_ADD = 'TRANSACTION_BULK_ADD'

export const ENROLLMENT_ADD = 'ENROLLMENT_ADD'
export const ENROLLMENT_BULK_ADD = 'ENROLLMENT_BULK_ADD'

export const BATCHSTUDENT_ADD = 'BATCHSTUDENT_ADD'
export const BATCHSTUDENT_BULK_ADD = 'BATCHSTUDENT_BULK_ADD'
export const BATCHSTUDENT_REMOVE = 'BATCHSTUDENT_REMOVE'
export const BATCHSTUDENT_UPDATE = 'BATCHSTUDENT_UPDATE'
export const BATCHSTUDENT_PAGE_ADD = 'BATCHSTUDENT_PAGE_ADD'
export const BATCHSTUDENT_PAGE_REMOVE = 'BATCHSTUDENT_PAGE_REMOVE'
export const BATCHSTUDENT_PAGE_REQUEST = 'BATCHSTUDENT_PAGE_REQUEST'
export const BATCHSTUDENT_PAGINATION_PURGE = 'BATCHSTUDENT_PAGINATION_PURGE'

export const BATCHCLASS_ADD = 'BATCHCLASS_ADD'
export const BATCHCLASS_BULK_ADD = 'BATCHCLASS_BULK_ADD'
export const BATCHCLASS_REMOVE = 'BATCHCLASS_REMOVE'
export const BATCHCLASS_UPDATE = 'BATCHCLASS_UPDATE'
export const BATCHCLASS_PAGE_ADD = 'BATCHCLASS_PAGE_ADD'
export const BATCHCLASS_PAGE_REMOVE = 'BATCHCLASS_PAGE_REMOVE'
export const BATCHCLASS_PAGE_REQUEST = 'BATCHCLASS_PAGE_REQUEST'
export const BATCHCLASS_PAGINATION_PURGE = 'BATCHCLASS_PAGINATION_PURGE'

export const BATCHCLASSFEE_ADD = 'BATCHCLASSFEE_ADD'
export const BATCHCLASSFEE_BULK_ADD = 'BATCHCLASSFEE_BULK_ADD'
export const BATCHCLASSFEE_REMOVE = 'BATCHCLASSFEE_REMOVE'
export const BATCHCLASSFEE_UPDATE = 'BATCHCLASSFEE_UPDATE'
export const BATCHCLASSFEE_PAGE_ADD = 'BATCHCLASSFEE_PAGE_ADD'
export const BATCHCLASSFEE_PAGE_REMOVE = 'BATCHCLASSFEE_PAGE_REMOVE'
export const BATCHCLASSFEE_PAGE_REQUEST = 'BATCHCLASSFEE_PAGE_REQUEST'
export const BATCHCLASSFEE_PAGINATION_PURGE = 'BATCHCLASSFEE_PAGINATION_PURGE'

export const BATCHCLASSENROLLMENT_ADD = 'BATCHCLASSENROLLMENT_ADD'
export const BATCHCLASSENROLLMENT_BULK_ADD = 'BATCHCLASSENROLLMENT_BULK_ADD'
export const BATCHCLASSENROLLMENT_REMOVE = 'BATCHCLASSENROLLMENT_REMOVE'
export const BATCHCLASSENROLLMENT_UPDATE = 'BATCHCLASSENROLLMENT_UPDATE'
export const BATCHCLASSENROLLMENT_PAGE_ADD = 'BATCHCLASSENROLLMENT_PAGE_ADD'
export const BATCHCLASSENROLLMENT_PAGE_REMOVE =
  'BATCHCLASSENROLLMENT_PAGE_REMOVE'
export const BATCHCLASSENROLLMENT_PAGE_REQUEST =
  'BATCHCLASSENROLLMENT_PAGE_REQUEST'
export const BATCHCLASSENROLLMENT_PAGINATION_PURGE =
  'BATCHCLASSENROLLMENT_PAGINATION_PURGE'

export const BATCHCLASSENROLLMENT_NEXT_SERIAL_SET =
  'BATCHCLASSENROLLMENT_NEXT_SERIAL_SET'

export const BATCHCLASSPAYMENT_ADD = 'BATCHCLASSPAYMENT_ADD'
export const BATCHCLASSPAYMENT_BULK_ADD = 'BATCHCLASSPAYMENT_BULK_ADD'
export const BATCHCLASSPAYMENT_REMOVE = 'BATCHCLASSPAYMENT_REMOVE'
export const BATCHCLASSPAYMENT_UPDATE = 'BATCHCLASSPAYMENT_UPDATE'
export const BATCHCLASSPAYMENT_PAGE_ADD = 'BATCHCLASSPAYMENT_PAGE_ADD'
export const BATCHCLASSPAYMENT_PAGE_REMOVE = 'BATCHCLASSPAYMENT_PAGE_REMOVE'
export const BATCHCLASSPAYMENT_PAGE_REQUEST = 'BATCHCLASSPAYMENT_PAGE_REQUEST'
export const BATCHCLASSPAYMENT_PAGINATION_PURGE =
  'BATCHCLASSPAYMENT_PAGINATION_PURGE'

export const BATCHCOURSE_ADD = 'BATCHCOURSE_ADD'
export const BATCHCOURSE_BULK_ADD = 'BATCHCOURSE_BULK_ADD'
export const BATCHCOURSE_REMOVE = 'BATCHCOURSE_REMOVE'
export const BATCHCOURSE_UPDATE = 'BATCHCOURSE_UPDATE'
export const BATCHCOURSE_PAGE_ADD = 'BATCHCOURSE_PAGE_ADD'
export const BATCHCOURSE_PAGE_REMOVE = 'BATCHCOURSE_PAGE_REMOVE'
export const BATCHCOURSE_PAGE_REQUEST = 'BATCHCOURSE_PAGE_REQUEST'
export const BATCHCOURSE_PAGINATION_PURGE = 'BATCHCOURSE_PAGINATION_PURGE'

export const BATCHCOURSEENROLLMENT_ADD = 'BATCHCOURSEENROLLMENT_ADD'
export const BATCHCOURSEENROLLMENT_BULK_ADD = 'BATCHCOURSEENROLLMENT_BULK_ADD'
export const BATCHCOURSEENROLLMENT_REMOVE = 'BATCHCOURSEENROLLMENT_REMOVE'
export const BATCHCOURSEENROLLMENT_UPDATE = 'BATCHCOURSEENROLLMENT_UPDATE'
export const BATCHCOURSEENROLLMENT_PAGE_ADD = 'BATCHCOURSEENROLLMENT_PAGE_ADD'
export const BATCHCOURSEENROLLMENT_PAGE_REMOVE =
  'BATCHCOURSEENROLLMENT_PAGE_REMOVE'
export const BATCHCOURSEENROLLMENT_PAGE_REQUEST =
  'BATCHCOURSEENROLLMENT_PAGE_REQUEST'
export const BATCHCOURSEENROLLMENT_PAGINATION_PURGE =
  'BATCHCOURSEENROLLMENT_PAGINATION_PURGE'

export const BATCHCOURSEENROLLMENT_NEXT_SERIAL_SET =
  'BATCHCOURSEENROLLMENT_NEXT_SERIAL_SET'

export const BATCHCOURSEPAYMENT_ADD = 'BATCHCOURSEPAYMENT_ADD'
export const BATCHCOURSEPAYMENT_BULK_ADD = 'BATCHCOURSEPAYMENT_BULK_ADD'
export const BATCHCOURSEPAYMENT_REMOVE = 'BATCHCOURSEPAYMENT_REMOVE'
export const BATCHCOURSEPAYMENT_UPDATE = 'BATCHCOURSEPAYMENT_UPDATE'
export const BATCHCOURSEPAYMENT_PAGE_ADD = 'BATCHCOURSEPAYMENT_PAGE_ADD'
export const BATCHCOURSEPAYMENT_PAGE_REMOVE = 'BATCHCOURSEPAYMENT_PAGE_REMOVE'
export const BATCHCOURSEPAYMENT_PAGE_REQUEST = 'BATCHCOURSEPAYMENT_PAGE_REQUEST'
export const BATCHCOURSEPAYMENT_PAGINATION_PURGE =
  'BATCHCOURSEPAYMENT_PAGINATION_PURGE'

export const BATCHCOURSEPAYMENT_REMINDER_ADD = 'BATCHCOURSEPAYMENT_REMINDER_ADD'
export const BATCHCOURSEPAYMENT_REMINDER_SET_ALL =
  'BATCHCOURSEPAYMENT_REMINDER_SET_ALL'
// export const BATCHFEE_PAGE_ADD = 'BATCHFEE_PAGE_ADD'
// export const BATCHFEE_PAGE_REMOVE = 'BATCHFEE_PAGE_REMOVE'
// export const BATCHFEE_PAGE_REQUEST = 'BATCHFEE_PAGE_REQUEST'
// export const BATCHFEE_PAGINATION_PURGE = 'BATCHFEE_PAGINATION_PURGE'

export const BATCHPAYMENT_ADD = 'BATCHPAYMENT_ADD'
export const BATCHPAYMENT_BULK_ADD = 'BATCHPAYMENT_BULK_ADD'
export const BATCHPAYMENT_REMOVE = 'BATCHPAYMENT_REMOVE'
export const BATCHPAYMENT_UPDATE = 'BATCHPAYMENT_UPDATE'
// export const BATCHPAYMENT_PAGE_ADD = 'BATCHPAYMENT_PAGE_ADD'
// export const BATCHPAYMENT_PAGE_REMOVE = 'BATCHPAYMENT_PAGE_REMOVE'
// export const BATCHPAYMENT_PAGE_REQUEST = 'BATCHPAYMENT_PAGE_REQUEST'
// export const BATCHPAYMENT_PAGINATION_PURGE = 'BATCHPAYMENT_PAGINATION_PURGE'
