import { combineReducers } from 'redux'
import {
  BATCHCLASS_PAGE_ADD,
  BATCHCLASS_PAGE_REMOVE,
  BATCHCLASS_PAGE_REQUEST,
  BATCHCLASS_PAGINATION_PURGE,
  // BATCHFEE_PAGE_ADD,
  // BATCHFEE_PAGE_REMOVE,
  // BATCHFEE_PAGE_REQUEST,
  // BATCHFEE_PAGINATION_PURGE,
  // BATCHPAYMENT_PAGE_ADD,
  // BATCHPAYMENT_PAGE_REMOVE,
  // BATCHPAYMENT_PAGE_REQUEST,
  // BATCHPAYMENT_PAGINATION_PURGE,
  BATCHSTUDENT_PAGE_ADD,
  BATCHSTUDENT_PAGE_REMOVE,
  BATCHSTUDENT_PAGE_REQUEST,
  BATCHSTUDENT_PAGINATION_PURGE,
  COURSETAG_PAGE_ADD,
  COURSETAG_PAGE_REMOVE,
  COURSETAG_PAGE_REQUEST,
  COURSETAG_PAGINATION_PURGE,
  COURSE_PAGE_ADD,
  COURSE_PAGE_REMOVE,
  COURSE_PAGE_REQUEST,
  COURSE_PAGINATION_PURGE,
  MCQTAG_PAGE_ADD,
  MCQTAG_PAGE_REMOVE,
  MCQTAG_PAGE_REQUEST,
  MCQTAG_PAGINATION_PURGE,
  MCQ_PAGE_ADD,
  MCQ_PAGE_REMOVE,
  MCQ_PAGE_REQUEST,
  MCQ_PAGINATION_PURGE,
  USER_PAGE_ADD,
  USER_PAGE_REMOVE,
  USER_PAGE_REQUEST,
  USER_PAGINATION_PURGE
} from 'store/actions/actionTypes.js'
import getPaginationReducer from './helpers/get-pagination-reducer.js'

const batchClasses = getPaginationReducer({
  ADD: BATCHCLASS_PAGE_ADD,
  REMOVE: BATCHCLASS_PAGE_REMOVE,
  REQUEST: BATCHCLASS_PAGE_REQUEST,
  PURGE: BATCHCLASS_PAGINATION_PURGE
})

// const batchFees = getPaginationReducer({
//   ADD: BATCHFEE_PAGE_ADD,
//   REMOVE: BATCHFEE_PAGE_REMOVE,
//   REQUEST: BATCHFEE_PAGE_REQUEST,
//   PURGE: BATCHFEE_PAGINATION_PURGE
// })

// const batchPayments = getPaginationReducer({
//   ADD: BATCHPAYMENT_PAGE_ADD,
//   REMOVE: BATCHPAYMENT_PAGE_REMOVE,
//   REQUEST: BATCHPAYMENT_PAGE_REQUEST,
//   PURGE: BATCHPAYMENT_PAGINATION_PURGE
// })

const batchStudents = getPaginationReducer({
  ADD: BATCHSTUDENT_PAGE_ADD,
  REMOVE: BATCHSTUDENT_PAGE_REMOVE,
  REQUEST: BATCHSTUDENT_PAGE_REQUEST,
  PURGE: BATCHSTUDENT_PAGINATION_PURGE
})

const courses = getPaginationReducer({
  ADD: COURSE_PAGE_ADD,
  REMOVE: COURSE_PAGE_REMOVE,
  REQUEST: COURSE_PAGE_REQUEST,
  PURGE: COURSE_PAGINATION_PURGE
})

const courseTags = getPaginationReducer({
  ADD: COURSETAG_PAGE_ADD,
  REMOVE: COURSETAG_PAGE_REMOVE,
  REQUEST: COURSETAG_PAGE_REQUEST,
  PURGE: COURSETAG_PAGINATION_PURGE
})

const mcqs = getPaginationReducer({
  ADD: MCQ_PAGE_ADD,
  REMOVE: MCQ_PAGE_REMOVE,
  REQUEST: MCQ_PAGE_REQUEST,
  PURGE: MCQ_PAGINATION_PURGE
})

const mcqTags = getPaginationReducer({
  ADD: MCQTAG_PAGE_ADD,
  REMOVE: MCQTAG_PAGE_REMOVE,
  REQUEST: MCQTAG_PAGE_REQUEST,
  PURGE: MCQTAG_PAGINATION_PURGE
})

const users = getPaginationReducer({
  ADD: USER_PAGE_ADD,
  REMOVE: USER_PAGE_REMOVE,
  REQUEST: USER_PAGE_REQUEST,
  PURGE: USER_PAGINATION_PURGE
})

const paginationReducer = combineReducers({
  batchClasses,
  // batchFees,
  // batchPayments,
  batchStudents,
  courses,
  courseTags,
  mcqs,
  mcqTags,
  users
})

export default paginationReducer
