import { combineReducers } from 'redux'
import {
  BATCHCLASSENROLLMENT_PAGE_ADD,
  BATCHCLASSENROLLMENT_PAGE_REMOVE,
  BATCHCLASSENROLLMENT_PAGE_REQUEST,
  BATCHCLASSENROLLMENT_PAGINATION_PURGE,
  BATCHCLASSFEE_PAGE_ADD,
  BATCHCLASSFEE_PAGE_REMOVE,
  BATCHCLASSFEE_PAGE_REQUEST,
  BATCHCLASSFEE_PAGINATION_PURGE,
  BATCHCLASS_PAGE_ADD,
  BATCHCLASS_PAGE_REMOVE,
  BATCHCLASS_PAGE_REQUEST,
  BATCHCLASS_PAGINATION_PURGE,
  BATCHCOURSEENROLLMENT_PAGE_ADD,
  BATCHCOURSEENROLLMENT_PAGE_REMOVE,
  BATCHCOURSEENROLLMENT_PAGE_REQUEST,
  BATCHCOURSEENROLLMENT_PAGINATION_PURGE,
  BATCHCOURSE_PAGE_ADD,
  BATCHCOURSE_PAGE_REMOVE,
  BATCHCOURSE_PAGE_REQUEST,
  BATCHCOURSE_PAGINATION_PURGE,
  BATCHSTUDENT_PAGE_ADD,
  BATCHSTUDENT_PAGE_REMOVE,
  BATCHSTUDENT_PAGE_REQUEST,
  BATCHSTUDENT_PAGINATION_PURGE,
  COURSETAG_PAGE_ADD,
  COURSETAG_PAGE_REMOVE,
  COURSETAG_PAGE_REQUEST,
  COURSETAG_PAGINATION_PURGE,
  COURSE_PAGE_ADD,
  COURSE_PAGE_REMOVE,
  COURSE_PAGE_REQUEST,
  COURSE_PAGINATION_PURGE,
  MCQTAG_PAGE_ADD,
  MCQTAG_PAGE_REMOVE,
  MCQTAG_PAGE_REQUEST,
  MCQTAG_PAGINATION_PURGE,
  MCQ_PAGE_ADD,
  MCQ_PAGE_REMOVE,
  MCQ_PAGE_REQUEST,
  MCQ_PAGINATION_PURGE,
  USER_PAGE_ADD,
  USER_PAGE_REMOVE,
  USER_PAGE_REQUEST,
  USER_PAGINATION_PURGE
} from 'store/actions/actionTypes'
import getPaginationReducer from './helpers/get-pagination-reducer'

const batchClasses = getPaginationReducer({
  ADD: BATCHCLASS_PAGE_ADD,
  REMOVE: BATCHCLASS_PAGE_REMOVE,
  REQUEST: BATCHCLASS_PAGE_REQUEST,
  PURGE: BATCHCLASS_PAGINATION_PURGE
})

const batchClassFees = getPaginationReducer({
  ADD: BATCHCLASSFEE_PAGE_ADD,
  REMOVE: BATCHCLASSFEE_PAGE_REMOVE,
  REQUEST: BATCHCLASSFEE_PAGE_REQUEST,
  PURGE: BATCHCLASSFEE_PAGINATION_PURGE
})

const batchClassEnrollments = getPaginationReducer({
  ADD: BATCHCLASSENROLLMENT_PAGE_ADD,
  REMOVE: BATCHCLASSENROLLMENT_PAGE_REMOVE,
  REQUEST: BATCHCLASSENROLLMENT_PAGE_REQUEST,
  PURGE: BATCHCLASSENROLLMENT_PAGINATION_PURGE
})

const batchCourses = getPaginationReducer({
  ADD: BATCHCOURSE_PAGE_ADD,
  REMOVE: BATCHCOURSE_PAGE_REMOVE,
  REQUEST: BATCHCOURSE_PAGE_REQUEST,
  PURGE: BATCHCOURSE_PAGINATION_PURGE
})

const batchCourseEnrollments = getPaginationReducer({
  ADD: BATCHCOURSEENROLLMENT_PAGE_ADD,
  REMOVE: BATCHCOURSEENROLLMENT_PAGE_REMOVE,
  REQUEST: BATCHCOURSEENROLLMENT_PAGE_REQUEST,
  PURGE: BATCHCOURSEENROLLMENT_PAGINATION_PURGE
})

const batchStudents = getPaginationReducer({
  ADD: BATCHSTUDENT_PAGE_ADD,
  REMOVE: BATCHSTUDENT_PAGE_REMOVE,
  REQUEST: BATCHSTUDENT_PAGE_REQUEST,
  PURGE: BATCHSTUDENT_PAGINATION_PURGE
})

const courses = getPaginationReducer({
  ADD: COURSE_PAGE_ADD,
  REMOVE: COURSE_PAGE_REMOVE,
  REQUEST: COURSE_PAGE_REQUEST,
  PURGE: COURSE_PAGINATION_PURGE
})

const courseTags = getPaginationReducer({
  ADD: COURSETAG_PAGE_ADD,
  REMOVE: COURSETAG_PAGE_REMOVE,
  REQUEST: COURSETAG_PAGE_REQUEST,
  PURGE: COURSETAG_PAGINATION_PURGE
})

const mcqs = getPaginationReducer({
  ADD: MCQ_PAGE_ADD,
  REMOVE: MCQ_PAGE_REMOVE,
  REQUEST: MCQ_PAGE_REQUEST,
  PURGE: MCQ_PAGINATION_PURGE
})

const mcqTags = getPaginationReducer({
  ADD: MCQTAG_PAGE_ADD,
  REMOVE: MCQTAG_PAGE_REMOVE,
  REQUEST: MCQTAG_PAGE_REQUEST,
  PURGE: MCQTAG_PAGINATION_PURGE
})

const users = getPaginationReducer({
  ADD: USER_PAGE_ADD,
  REMOVE: USER_PAGE_REMOVE,
  REQUEST: USER_PAGE_REQUEST,
  PURGE: USER_PAGINATION_PURGE
})

const paginationReducer = combineReducers({
  batchClasses,
  batchClassFees,
  batchClassEnrollments,
  batchCourses,
  batchCourseEnrollments,
  batchStudents,
  courses,
  courseTags,
  mcqs,
  mcqTags,
  users
})

export default paginationReducer
